export const ADD_JOBS = "ADD_JOBS";
export const ADD_JOBS_LOADING = "ADD_JOBS_LOADING";
export const ADD_JOBS_SUCCESS = "ADD_JOBS_SUCCESS";
export const ADD_JOBS_ERROR = "ADD_JOBS_ERROR";
export const GET_JOBS_LOADING = "GET_JOBS_LOADING";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";
export const GET_JOBS_ERROR = "GET_JOBS_ERROR"; 

